/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.dis.interfaz.vistactrl.anyadirtarjetadescriptora;

import java.awt.CardLayout;
import uva.dis.persistencia.TarjetaDeProductoDTO;


/**
 *
 * @author Admin
 */
public final class AnyadirTarjetaDescriptoraVista extends javax.swing.JFrame {

    private ControladorVistaAnyadirTarjetaDescriptora tarjetaController;
    private TarjetaDeProductoDTO tarjetaActual;
    private CardLayout cardLayout;
    private boolean seleccionado = false;

    public AnyadirTarjetaDescriptoraVista() {
        initComponents();
        mostrarError("");
        cardLayout = (CardLayout) jPanel2.getLayout();

        crearTarjetaButton.setVisible(false);
        tarjetaController = new ControladorVistaAnyadirTarjetaDescriptora(this);
        String empleadoActual = tarjetaController.getEmpleadoActual();
        mostrarUsuario(empleadoActual);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        volverButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        usuarioActualLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        crearTarjetaButton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        jPanel21 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ingredientesTextArea = new javax.swing.JTextArea();
        jPanel18 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        unidadesComboBox = new javax.swing.JComboBox<>();
        jPanel25 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        alergenosTextArea = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        verDetallesButton = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DetallesTextArea = new javax.swing.JTextArea();
        jPanel30 = new javax.swing.JPanel();
        cancelarTarjetaButton = new javax.swing.JButton();
        confirmarTarjetaButton = new javax.swing.JButton();
        crearProductoButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        retroalimentacionLabel = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 100));
        setSize(new java.awt.Dimension(700, 600));
        java.awt.GridBagLayout layout1 = new java.awt.GridBagLayout();
        layout1.columnWeights = new double[] {1.0};
        layout1.rowWeights = new double[] {0.1, 0.85, 0.05};
        getContentPane().setLayout(layout1);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 1, 1));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        volverButton.setText("Volver");
        volverButton.setMaximumSize(new java.awt.Dimension(64, 22));
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        jPanel4.add(volverButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MEJOR NO TIRARLO");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel5, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 1, 1));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel6.setLayout(new java.awt.BorderLayout());

        usuarioActualLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usuarioActualLabel.setText("Usuario");
        usuarioActualLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(usuarioActualLabel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.CardLayout());

        java.awt.GridBagLayout jPanel7Layout1 = new java.awt.GridBagLayout();
        jPanel7Layout1.columnWeights = new double[] {1.0};
        jPanel7Layout1.rowWeights = new double[] {0.3, 0.1, 0.15, 0.15, 0.3};
        jPanel7.setLayout(jPanel7Layout1);

        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel8.add(jSeparator2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        jPanel7.add(jPanel8, gridBagConstraints);

        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Introduzca el nombre de la tarjeta sobre la que desea añadir un producto");
        jPanel10.add(jLabel7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel7.add(jPanel10, gridBagConstraints);

        jLabel8.setText("Nombre de la tarjeta:");
        jPanel11.add(jLabel8);

        nombreTextField.setText("                 ");
        nombreTextField.setPreferredSize(new java.awt.Dimension(120, 22));
        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });
        jPanel11.add(nombreTextField);
        nombreTextField.getAccessibleContext().setAccessibleDescription("");

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        jPanel11.add(buscarButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.15;
        jPanel7.add(jPanel11, gridBagConstraints);

        crearTarjetaButton.setText("Crear Tarjeta descriptora");
        crearTarjetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTarjetaButtonActionPerformed(evt);
            }
        });
        jPanel12.add(crearTarjetaButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.15;
        jPanel7.add(jPanel12, gridBagConstraints);

        jPanel13.setLayout(new java.awt.BorderLayout());
        jPanel13.add(jSeparator1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        jPanel7.add(jPanel13, gridBagConstraints);

        jPanel2.add(jPanel7, "card2");

        java.awt.GridBagLayout jPanel9Layout = new java.awt.GridBagLayout();
        jPanel9Layout.columnWeights = new double[] {1.0};
        jPanel9Layout.rowWeights = new double[] {0.1, 0.7, 0.2};
        jPanel9.setLayout(jPanel9Layout);

        jLabel2.setText("Nombre del producto");
        jPanel14.add(jLabel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel9.add(jPanel14, gridBagConstraints);

        java.awt.GridBagLayout jPanel15Layout = new java.awt.GridBagLayout();
        jPanel15Layout.columnWeights = new double[] {0.5, 0.5};
        jPanel15Layout.rowWeights = new double[] {1.0};
        jPanel15.setLayout(jPanel15Layout);

        java.awt.GridBagLayout jPanel17Layout = new java.awt.GridBagLayout();
        jPanel17Layout.columnWeights = new double[] {1.0};
        jPanel17Layout.rowWeights = new double[] {0.1, 0.4, 0.1, 0.4};
        jPanel17.setLayout(jPanel17Layout);

        jLabel5.setText("Descripción:");
        jPanel19.add(jLabel5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel17.add(jPanel19, gridBagConstraints);

        descripcionTextArea.setColumns(20);
        descripcionTextArea.setRows(5);
        jScrollPane5.setViewportView(descripcionTextArea);

        jPanel20.add(jScrollPane5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.4;
        jPanel17.add(jPanel20, gridBagConstraints);

        jLabel4.setText("Ingredientes:");
        jPanel21.add(jLabel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel17.add(jPanel21, gridBagConstraints);

        ingredientesTextArea.setColumns(20);
        ingredientesTextArea.setRows(5);
        jScrollPane4.setViewportView(ingredientesTextArea);

        jPanel22.add(jScrollPane4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.4;
        jPanel17.add(jPanel22, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel15.add(jPanel17, gridBagConstraints);

        java.awt.GridBagLayout jPanel18Layout = new java.awt.GridBagLayout();
        jPanel18Layout.columnWeights = new double[] {1.0};
        jPanel18Layout.rowWeights = new double[] {0.1, 0.4, 0.1, 0.4};
        jPanel18.setLayout(jPanel18Layout);

        jLabel6.setText("Unidades");
        jPanel23.add(jLabel6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel18.add(jPanel23, gridBagConstraints);

        unidadesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kilogramos", "litros", "unidades" }));
        jPanel24.add(unidadesComboBox);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.4;
        jPanel18.add(jPanel24, gridBagConstraints);

        jLabel9.setText("Alérgenos:");
        jPanel25.add(jLabel9);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel18.add(jPanel25, gridBagConstraints);

        alergenosTextArea.setColumns(20);
        alergenosTextArea.setRows(5);
        jScrollPane6.setViewportView(alergenosTextArea);

        jPanel26.add(jScrollPane6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.4;
        jPanel18.add(jPanel26, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel15.add(jPanel18, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        jPanel9.add(jPanel15, gridBagConstraints);

        verDetallesButton.setText("Ver detalles y confirmar");
        verDetallesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDetallesButtonActionPerformed(evt);
            }
        });
        jPanel16.add(verDetallesButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        jPanel9.add(jPanel16, gridBagConstraints);

        jPanel2.add(jPanel9, "card3");

        java.awt.GridBagLayout jPanel27Layout = new java.awt.GridBagLayout();
        jPanel27Layout.columnWeights = new double[] {1.0};
        jPanel27Layout.rowWeights = new double[] {0.1, 0.7, 0.2};
        jPanel27.setLayout(jPanel27Layout);

        jLabel10.setText("Detalles de tarjeta descriptora");
        jPanel28.add(jLabel10);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel27.add(jPanel28, gridBagConstraints);

        jPanel29.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 40));
        jPanel29.setLayout(new java.awt.BorderLayout());

        DetallesTextArea.setColumns(20);
        DetallesTextArea.setRows(5);
        jScrollPane1.setViewportView(DetallesTextArea);

        jPanel29.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        jPanel27.add(jPanel29, gridBagConstraints);

        cancelarTarjetaButton.setText("Cancelar");
        cancelarTarjetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarTarjetaButtonActionPerformed(evt);
            }
        });
        jPanel30.add(cancelarTarjetaButton);

        confirmarTarjetaButton.setText("Confirmar tarjeta descriptora");
        confirmarTarjetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarTarjetaButtonActionPerformed(evt);
            }
        });
        jPanel30.add(confirmarTarjetaButton);

        crearProductoButton.setText("Crear producto");
        crearProductoButton.setVisible(false);
        crearProductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearProductoButtonActionPerformed(evt);
            }
        });
        jPanel30.add(crearProductoButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        jPanel27.add(jPanel30, gridBagConstraints);

        jPanel2.add(jPanel27, "card4");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.85;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 5, 1));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        retroalimentacionLabel.setText("                                                                           ");
        jPanel3.add(retroalimentacionLabel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.05;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        tarjetaController.volverAVistaDeTrabajo();
        this.dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed

    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        tarjetaController.buscarTarjeta();
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void crearTarjetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTarjetaButtonActionPerformed
        tarjetaController.procesarCrearTarjeta();
    }//GEN-LAST:event_crearTarjetaButtonActionPerformed

    private void confirmarTarjetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarTarjetaButtonActionPerformed
        tarjetaController.confirmarCreacionTarjeta();
    }//GEN-LAST:event_confirmarTarjetaButtonActionPerformed

    private void cancelarTarjetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarTarjetaButtonActionPerformed
        tarjetaController.cancelarCreacionTarjeta();
    }//GEN-LAST:event_cancelarTarjetaButtonActionPerformed

    private void crearProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProductoButtonActionPerformed
        tarjetaController.iniciarCreacionProducto();
    }//GEN-LAST:event_crearProductoButtonActionPerformed

    private void verDetallesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDetallesButtonActionPerformed
        tarjetaController.previsualizarTarjeta();
    }//GEN-LAST:event_verDetallesButtonActionPerformed

    public void mostrarLabelYCard(String texto, String nombreCard) {
        cambiarNombreDelProducto(texto);
        cambiarACard(nombreCard);
    }

    public void ocultar() {
        setVisible(false);
    }

    public void setTarjetaActual(TarjetaDeProductoDTO tarjeta) {
        this.tarjetaActual = tarjeta;
    }

    public void mostrarBotonCrearTarjeta() {
        crearTarjetaButton.setVisible(true);
        crearTarjetaButton.setText("Crear tarjeta descriptora");
    }

    public void mostrarBotonVerDetalles() {
        crearTarjetaButton.setVisible(true);
        crearTarjetaButton.setText("Ver detalles");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DetallesTextArea;
    private javax.swing.JTextArea alergenosTextArea;
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton cancelarTarjetaButton;
    private javax.swing.JButton confirmarTarjetaButton;
    private javax.swing.JButton crearProductoButton;
    private javax.swing.JButton crearTarjetaButton;
    private javax.swing.JTextArea descripcionTextArea;
    private javax.swing.JTextArea ingredientesTextArea;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel retroalimentacionLabel;
    private javax.swing.JComboBox<String> unidadesComboBox;
    private javax.swing.JLabel usuarioActualLabel;
    private javax.swing.JButton verDetallesButton;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables

    public String getNombreProducto() {
        return nombreTextField.getText().trim();
    }

    public void mostrarError(String text) {
        retroalimentacionLabel.setText(text);
    }

    public void mostrarDetallesIngredientes(String detalles) {
        ingredientesTextArea.setText(detalles);
    }

    public void mostrarDetalles(String detalles) {
        DetallesTextArea.setText(detalles);
    }

    public void mostrarUsuario(String texto) {
        usuarioActualLabel.setText(texto);
    }

    public void setSeleccionado(boolean selec) {
        this.seleccionado = selec;
    }

    public boolean getSeleccionado() {
        return this.seleccionado;
    }

    private void mostrarLabelYCard(javax.swing.JLabel label, String texto, String nombreCard) {
        label.setText(texto);
        cambiarACard(nombreCard);
        mostrarError("");
    }

    public String getDescripcion() {
        return descripcionTextArea.getText();
    }

    public String getAlergenos() {
        return alergenosTextArea.getText();
    }

    public String getIngredientes() {
        return ingredientesTextArea.getText();
    }

    public String getUnidadSeleccionada() {
        return (String) unidadesComboBox.getSelectedItem();
    }

    public String getTextoCrearTarjeta() {
        return crearTarjetaButton.getText();
    }

    public TarjetaDeProductoDTO getTarjetaActual() {
        return tarjetaActual;
    }

    public void mostrarDetallesExistente() {
        mostrarDetalles(tarjetaController.formatearDetalles(tarjetaActual));
        cancelarTarjetaButton.setVisible(false);
        confirmarTarjetaButton.setVisible(false);
        mostrarError("");
        cambiarACard("card4");
    }

    public void prepararFormularioNuevaTarjeta() {
        String nombre = getNombreProducto();
        cambiarNombreDelProducto("Producto: " + nombre);
        mostrarError("");
        mostrarLabelYCard(jLabel2, "Producto: " + nombre, "card3");
    }

    public void cambiarACard(String nombreCard) {
        cardLayout.show(jPanel2, nombreCard);
    }

    public void ocultarBotonesConfirmacion() {
        confirmarTarjetaButton.setVisible(false);
        cancelarTarjetaButton.setVisible(false);
    }

    public void mostrarBotonCrearProducto() {
        crearProductoButton.setVisible(true);
    }
    
    public void cambiarNombreDelProducto(String text){
        jLabel2.setText(text);
    }
 
    

}
