/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.dis.interfaz.vistactrl.prepararpedido;

import javax.swing.DefaultListModel;
import uva.dis.persistencia.PedidoDTO;

/**
 *
 * @author Admin
 */
public final class PrepararPedidoVista extends javax.swing.JFrame {

    private ControladorVistaPrepararPedido pedidoController;

    private boolean seleccionado = false;

    public PrepararPedidoVista() {
        initComponents();
        mostrarError("");

        pedidoController = new ControladorVistaPrepararPedido(this);
        pedidoController.inicializarVista();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        volverButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        usuarioActualLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pedidosList = new javax.swing.JList<>();
        seleccionarButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detallesTextArea = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        prepararPedidoButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        retroalimentacionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 100));
        setSize(new java.awt.Dimension(700, 600));
        java.awt.GridBagLayout layout1 = new java.awt.GridBagLayout();
        layout1.rowWeights = new double[] {0.1, 0.85, 0.05};
        getContentPane().setLayout(layout1);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 1, 1));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        volverButton.setText("Volver");
        volverButton.setMaximumSize(new java.awt.Dimension(64, 22));
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        jPanel4.add(volverButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MEJOR NO TIRARLO");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel5, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 1, 1));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel6.setLayout(new java.awt.BorderLayout());

        usuarioActualLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usuarioActualLabel.setText("Usuario");
        usuarioActualLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(usuarioActualLabel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setMaximumSize(null);
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        java.awt.GridBagLayout jPanel8Layout = new java.awt.GridBagLayout();
        jPanel8Layout.rowWeights = new double[] {0.05, 0.95};
        jPanel8.setLayout(jPanel8Layout);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pedidos realizados:");
        jPanel12.add(jLabel2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel8.add(jPanel12, gridBagConstraints);

        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 50, 50, 50));
        jPanel13.setLayout(new java.awt.BorderLayout());

        pedidosList.setPreferredSize(new java.awt.Dimension(180, 90));
        jScrollPane2.setViewportView(pedidosList);

        jPanel13.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        seleccionarButton.setText("Seleccionar");
        seleccionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarButtonActionPerformed(evt);
            }
        });
        jPanel13.add(seleccionarButton, java.awt.BorderLayout.PAGE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        jPanel8.add(jPanel13, gridBagConstraints);

        jPanel2.add(jPanel8);

        java.awt.GridBagLayout jPanel7Layout = new java.awt.GridBagLayout();
        jPanel7Layout.rowWeights = new double[] {0.1, 0.75, 0.15};
        jPanel7.setLayout(jPanel7Layout);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Detales del pedido:");
        jPanel9.add(jLabel6, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel7.add(jPanel9, gridBagConstraints);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 50, 20, 50));
        jPanel10.setLayout(new java.awt.BorderLayout());

        detallesTextArea.setColumns(20);
        detallesTextArea.setRows(5);
        jScrollPane1.setViewportView(detallesTextArea);

        jPanel10.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.75;
        jPanel7.add(jPanel10, gridBagConstraints);

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 15, 40));

        prepararPedidoButton.setText("Preparar pedido");
        prepararPedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prepararPedidoButtonActionPerformed(evt);
            }
        });
        jPanel11.add(prepararPedidoButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.15;
        jPanel7.add(jPanel11, gridBagConstraints);

        jPanel2.add(jPanel7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.85;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 5, 1));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        retroalimentacionLabel.setText("El pedido seleccionado se ha actualizado como preparado");
        jPanel3.add(retroalimentacionLabel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.05;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {
        pedidoController.volverAVistaDeTrabajo();
        this.dispose();
    }

    private void prepararPedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        pedidoController.prepararPedido();
    }

    private void seleccionarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        pedidoController.seleccionarPedido();
    }


    private javax.swing.JTextArea detallesTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<PedidoDTO> pedidosList;
    private javax.swing.JButton prepararPedidoButton;
    private javax.swing.JLabel retroalimentacionLabel;
    private javax.swing.JButton seleccionarButton;
    private javax.swing.JLabel usuarioActualLabel;
    private javax.swing.JButton volverButton;
    


    public void mostrarError(String text) {
        retroalimentacionLabel.setText(text);
    }

    public void mostrarDetalles(String detalles) {
        detallesTextArea.setText(detalles);
    }

    public void mostrarUsuario(String texto) {
        usuarioActualLabel.setText(texto);
    }

    public void mostrarLista(DefaultListModel<PedidoDTO> lista) {
        pedidosList.setModel(lista);
    }

    public PedidoDTO getPedidoSeleccionado() {
        return pedidosList.getSelectedValue();
    }

    public void setSeleccionado(boolean selec) {
        this.seleccionado = selec;
    }

    public boolean getSeleccionado() {
        return this.seleccionado;
    }
}
