
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[302] =
    {   0,
        0,    0,   62,   60,   58,   57,   60,   60,   60,   49,
       50,   35,   33,   48,   34,   45,   36,   37,   46,   31,
       31,   31,   56,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   53,   54,   39,
       39,   39,   39,   39,   39,   39,   51,   55,   52,   60,
       58,    0,   41,   32,    0,   40,   59,    0,    0,   37,
       39,   39,   47,   31,   39,   39,   39,   39,   39,   39,
       39,    8,    7,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   28,
       39,    0,   59,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   38,    0,   38,   18,   39,   39,
       39,    5,   39,   39,   39,   39,    2,    6,   39,   39,
       39,    3,   39,   39,   39,   39,   17,   39,   39,   39,
       30,   39,   29,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   38,   39,   39,   39,
       10,   39,   39,   39,   16,   39,   39,    4,   22,   39,
       12,   39,   39,    9,   14,   39,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   27,    0,    0,    0,    0,

        0,    0,   39,   39,   39,   11,   15,   39,   39,   39,
       39,   39,   39,   39,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   39,   39,   39,   39,   25,
       39,   13,   39,   24,   39,   43,   44,   42,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   23,   39,    1,   21,   26,   39,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       39,    1,   19,    0,    0,    0,    0,    0,    0,   39,
        0,    0,    0,    0,   20,    0,    0,    0,    0,    0,

        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    5,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
       18,   19,    1,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   30,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   30,   42,   43,   30,
       44,    1,   45,    1,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   28,   54,   55,   30,   56,   57,   58,
       59,   60,   61,   62,   63,   64,   65,   66,   30,   67,
       68,   69,   70,   71,   72,    1,    1,   73,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   74,   75,    1,    1,   76,   77,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   78,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[79] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    3,    1,    3,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    1,    4,    5,    6,    7,    7,    1
    } ;

static const flex_int16_t yy_base[309] =
    {   0,
        0,    0,  761,  762,  758,  762,  755,  753,  751,  762,
      762,  762,  762,  762,   67,  762,  762,   69,  740,   69,
      762,  737,  762,   70,   78,   79,   82,   85,   89,   90,
      115,   95,   98,  116,  119,  138,  143,  762,  762,  111,
      161,  168,  144,  151,  172,  154,  762,  762,  762,  681,
      751,  748,  747,  762,  744,  743,    0,  181,  733,  216,
      171,  196,  762,  762,  234,  235,  239,  238,  179,  242,
      243,  185,  247,  246,  252,  266,  263,  211,  291,  292,
      270,  308,  269,  257,  280,  303,  304,  312,  324,  186,
      328,  268,    0,   71,  686,  676,  291,  288,  693,   50,

      679,  687,  682,  122,  340,  717,  355,  347,  350,  360,
      361,  364,  368,  367,  372,  373,  376,  384,  388,  391,
      392,  396,  402,  426,  415,  429,  416,  432,  435,  438,
      439,  446,  449,  653,  651,  644,  655,  123,   49,  654,
      643,  657,  641,  652,  675,  648,  635,  630,  638,  631,
      638,  138,  637,  623,  634,  460,  675,  460,  463,  467,
      466,  470,  484,  471,  488,  492,  493,  497,  502,  506,
      510,  515,  516,  519,  520,  526,  611,  615,  609,  612,
      606,  610,  631,  633,  627,  619,  616,  610,  609,  607,
      649,  613,  611,  605,  602,  762,  640,  328,  612,  607,

      606,  599,  530,  533,  534,  541,  542,  546,  547,  552,
      556,  559,  572,  562,  570,  567,  560,  566,  568,  347,
      567,  540,  530,  525,  524,  522,  503,  504,  501,  485,
      471,  457,  467,  450,  458,  573,  568,  580,  585,  589,
      598,  592,  603,  597,  616,  762,  762,  762,  450,  425,
      438,  402,  413,  398,  403,  383,  372,  373,  393,  383,
      359,  355,  353,  617,  622,  623,  627,  630,  635,  343,
      312,  309,  289,  268,  276,  254,  238,  246,  228,  238,
      643,  762,  642,  220,  210,  155,  159,  160,  154,  648,
      151,  137,  118,  107,  651,  101,  112,  105,   67,   63,

      762,  706,  713,   82,  720,  727,  734,  741
    } ;

static const flex_int16_t yy_def[309] =
    {   0,
      301,    1,  301,  301,  301,  301,  302,  301,  303,  301,
      301,  301,  301,  301,  301,  301,  301,  304,  301,  301,
      301,  301,  301,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  301,  301,  304,
      304,  304,  304,  304,  304,  304,  301,  301,  301,  301,
      301,  302,  301,  301,  303,  301,  305,  301,  301,  304,
      304,  304,  301,  301,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  301,  305,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  306,  307,  308,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  306,  301,  307,  301,
      308,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  304,  304,  304,  304,  304,  304,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      304,  301,  304,  301,  301,  301,  301,  301,  301,  304,
      301,  301,  301,  301,  304,  301,  301,  301,  301,  301,

        0,  301,  301,  301,  301,  301,  301,  301
    } ;

static const flex_int16_t yy_nxt[841] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   24,   24,   30,   24,
       24,   31,   32,   33,   34,   24,   35,   36,   37,   24,
       24,   24,   24,   38,   39,    4,   40,   25,   26,   41,
       28,   29,   24,   42,   24,   31,   43,   44,   45,   34,
       24,   35,   36,   37,   24,   24,   46,   24,   24,   47,
       48,   49,    4,    4,    4,    4,    4,   50,   57,   59,
      301,   59,  301,   60,   61,   58,   64,   64,  301,  301,
      301,  301,  301,   62,  301,  301,  148,  301,   65,  301,

      301,  301,  301,  149,  186,  301,   68,  301,  301,   71,
      301,   66,   67,  187,  196,   72,   69,   70,  196,   62,
       76,  301,   73,  301,   65,  301,  301,  301,  301,  301,
      137,  301,   68,  138,   75,   71,   66,   67,  300,   74,
       69,   72,   70,   79,  184,  299,   76,   73,  301,   77,
      301,  196,   78,  301,  301,  301,  301,  298,   84,   75,
      185,  301,   80,  301,  301,   74,  301,  297,   85,   79,
       82,  301,  153,  301,   77,  154,   81,   78,  301,   83,
      301,  301,  301,  301,  301,   68,  155,  196,   80,  301,
       75,  301,  199,   72,   76,  301,  301,  301,  301,  296,

       73,   81,   88,  200,   83,  106,  301,  106,  301,   89,
      107,   68,   91,  294,   86,   75,  113,  293,  292,   72,
       76,  301,  196,  301,   87,   73,   59,   94,   59,   95,
       60,   96,   97,   90,   98,  122,   99,  100,  101,  102,
       62,  113,  103,  104,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      108,  122,  301,  112,  301,  114,   62,  301,  109,  301,
      110,  111,  196,  301,  115,  301,  301,  291,  301,  301,
      301,  301,  301,  119,  118,  116,  108,  117,  196,  112,
      301,  114,  301,  109,  110,  289,  111,  120,  115,  288,

      121,  301,  301,  301,  301,  287,  128,  119,  130,  118,
      116,  123,  117,  301,  301,  301,  301,  286,  301,  131,
      301,  120,  301,  125,  301,  121,  196,  126,  124,   90,
      127,  128,  129,  130,  301,  196,  301,  123,  301,  285,
      301,  134,  135,  136,  141,  144,  142,  125,  231,  143,
      145,  146,  126,  124,  105,  127,  232,  301,  129,  301,
      301,  131,  301,  132,  156,  301,  196,  301,  131,  107,
      301,  301,  301,  301,  301,  196,  301,  301,  301,  301,
      301,  158,  301,  301,  301,  301,  301,  133,  301,   90,
      156,  159,  161,  284,  301,  162,  301,  164,  301,  160,

      301,  301,  301,  301,  301,  158,  301,  250,  301,  163,
      196,  166,  301,  278,  301,  159,  196,  280,  161,  165,
      162,  279,  196,  164,  160,  301,  301,  301,  301,  167,
      168,  277,  276,  169,  163,  275,  301,  166,  301,  301,
      171,  301,  301,  165,  301,  301,  274,  301,  301,  301,
      301,  301,  273,  196,  167,  168,  301,  169,  301,  301,
      173,  301,  175,  272,  196,  170,  171,  174,  172,  106,
      301,  106,  301,  301,  157,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  203,  173,  271,  204,  175,  270,
      170,  205,  174,  172,  301,  206,  301,  208,  301,  196,

      301,  176,  301,  301,  301,  301,  263,  301,  207,  301,
      203,  262,  301,  204,  301,  261,  301,  205,  301,  260,
      301,  206,  301,  208,  209,  301,  301,  301,  301,  301,
      301,  301,  301,  259,  207,  210,  301,  211,  301,  212,
      301,  258,  301,  301,  301,  301,  301,  257,  213,  209,
      236,  301,  301,  301,  301,  237,  301,  301,  301,  301,
      210,  211,  301,  256,  301,  212,  301,  255,  301,  301,
      239,  301,  301,  213,  301,  238,  236,  254,  301,  214,
      301,  237,  301,  301,  301,  301,  241,  253,  196,  240,
      301,  243,  301,  252,  242,  301,  239,  301,  244,  301,

      238,  301,  301,  196,  301,  264,  265,  301,  301,  301,
      301,  241,  245,  301,  240,  301,  243,  251,  266,  242,
      196,  267,  268,  249,  244,  269,  301,  301,  301,  301,
      264,  265,  301,  301,  301,  301,  248,  301,  282,  301,
      301,  247,  301,  266,  246,  301,  267,  301,  268,  196,
      281,  269,  301,  301,  301,  301,  235,  234,  301,  283,
      301,  301,  233,  301,  230,  196,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  281,  290,  220,   90,  219,
      295,  218,  217,  182,  216,  283,  180,  215,  178,  157,
      196,  202,  201,  198,  197,  196,  196,  195,  194,  193,

      192,  290,  191,  190,  189,  295,   52,  188,   52,   52,
       52,   52,   52,   55,  183,   55,   55,   55,   55,   55,
       93,  182,   93,   93,   93,   93,   93,  177,  180,  177,
      178,  157,  152,  177,  179,  151,  179,  150,  179,  147,
      179,  181,  140,  181,  139,  181,  181,  105,   55,   56,
       52,   53,   51,   92,   64,   63,   56,   54,   53,   51,
      301,    3,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301
    } ;

static const flex_int16_t yy_chk[841] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   15,   18,
       24,   18,   24,   18,  304,   15,   20,   20,   25,   26,
       25,   26,   27,   18,   27,   28,  100,   28,   25,   29,

       30,   29,   30,  100,  139,   32,   27,   32,   33,   29,
       33,   25,   26,  139,  300,   30,   28,   28,  299,   18,
       33,   40,   30,   40,   25,   31,   34,   31,   34,   35,
       94,   35,   27,   94,   32,   29,   25,   26,  298,   31,
       28,   30,   28,   35,  138,  297,   33,   30,   36,   34,
       36,  296,   34,   37,   43,   37,   43,  294,   40,   32,
      138,   44,   36,   44,   46,   31,   46,  293,   40,   35,
       37,   41,  104,   41,   34,  104,   36,   34,   42,   37,
       42,   61,   45,   61,   45,   41,  104,  292,   36,   69,
       44,   69,  152,   42,   45,   72,   90,   72,   90,  291,

       42,   36,   43,  152,   37,   62,   62,   62,   62,   44,
       62,   41,   46,  289,   41,   44,   69,  288,  287,   42,
       45,   78,  286,   78,   42,   42,   60,   58,   60,   58,
       60,   58,   58,   45,   58,   78,   58,   58,   58,   58,
       60,   69,   58,   58,   65,   66,   65,   66,   68,   67,
       68,   67,   70,   71,   70,   71,   74,   73,   74,   73,
       65,   78,   75,   68,   75,   70,   60,   84,   66,   84,
       67,   67,  285,   77,   71,   77,   76,  284,   76,   83,
       81,   83,   81,   75,   74,   73,   65,   73,  280,   68,
       85,   70,   85,   66,   67,  279,   67,   76,   71,  278,

       77,   79,   80,   79,   80,  277,   81,   75,   83,   74,
       73,   79,   73,   86,   87,   86,   87,  276,   82,   84,
       82,   76,   88,   80,   88,   77,  275,   80,   79,   85,
       80,   81,   82,   83,   89,  274,   89,   79,   91,  273,
       91,   92,   92,   92,   97,   98,   97,   80,  198,   97,
       98,   98,   80,   79,  105,   80,  198,  108,   82,  108,
      109,   88,  109,   87,  105,  107,  272,  107,   86,  107,
      110,  111,  110,  111,  112,  271,  112,  114,  113,  114,
      113,  109,  115,  116,  115,  116,  117,   89,  117,   91,
      105,  110,  113,  270,  118,  114,  118,  116,  119,  111,

      119,  120,  121,  120,  121,  109,  122,  220,  122,  115,
      220,  120,  123,  260,  123,  110,  263,  262,  113,  119,
      114,  260,  261,  116,  111,  125,  127,  125,  127,  120,
      121,  259,  258,  123,  115,  257,  124,  120,  124,  126,
      125,  126,  128,  119,  128,  129,  256,  129,  130,  131,
      130,  131,  255,  254,  120,  121,  132,  123,  132,  133,
      128,  133,  130,  253,  252,  124,  125,  129,  126,  156,
      158,  156,  158,  159,  156,  159,  161,  160,  161,  160,
      162,  164,  162,  164,  158,  128,  251,  159,  130,  250,
      124,  160,  129,  126,  163,  162,  163,  164,  165,  249,

      165,  132,  166,  167,  166,  167,  235,  168,  163,  168,
      158,  234,  169,  159,  169,  233,  170,  160,  170,  232,
      171,  162,  171,  164,  166,  172,  173,  172,  173,  174,
      175,  174,  175,  231,  163,  167,  176,  170,  176,  172,
      203,  230,  203,  204,  205,  204,  205,  229,  173,  166,
      203,  206,  207,  206,  207,  204,  208,  209,  208,  209,
      167,  170,  210,  228,  210,  172,  211,  227,  211,  212,
      208,  212,  214,  173,  214,  205,  203,  226,  237,  176,
      237,  204,  213,  236,  213,  236,  210,  225,  224,  209,
      238,  212,  238,  223,  211,  239,  208,  239,  213,  240,

      205,  240,  242,  222,  242,  236,  237,  244,  241,  244,
      241,  210,  214,  243,  209,  243,  212,  221,  238,  211,
      219,  239,  241,  218,  213,  243,  245,  264,  245,  264,
      236,  237,  265,  266,  265,  266,  217,  267,  266,  267,
      268,  216,  268,  238,  215,  269,  239,  269,  241,  202,
      265,  243,  283,  281,  283,  281,  201,  200,  290,  269,
      290,  295,  199,  295,  197,  195,  194,  193,  192,  191,
      190,  189,  188,  187,  186,  265,  281,  185,  245,  184,
      290,  183,  182,  181,  180,  269,  179,  178,  177,  157,
      155,  154,  153,  151,  150,  149,  148,  147,  146,  145,

      144,  281,  143,  142,  141,  290,  302,  140,  302,  302,
      302,  302,  302,  303,  137,  303,  303,  303,  303,  303,
      305,  136,  305,  305,  305,  305,  305,  306,  135,  306,
      134,  106,  103,  306,  307,  102,  307,  101,  307,   99,
      307,  308,   96,  308,   95,  308,  308,   59,   56,   55,
       53,   52,   51,   50,   22,   19,    9,    8,    7,    5,
        3,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "aLexico.l"
#line 2 "aLexico.l"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "aSintactico.tab.h"
#define OPERATOR 1000

extern void yyerror(const char *s);
extern int yylineno;
extern YYSTYPE yylval;
int columna_actual = 1;

char* safe_strdup(const char* s) {
    char* new_s = strdup(s);
    if (!new_s) {
        perror("strdup failed");
        exit(EXIT_FAILURE);
    }
    return new_s;
}

typedef struct _simbolo {
    struct _simbolo *sig;
    char nombre[50];
    int valor;
    int tipo;
    int linea;
    int columna;
    char context[50]; // Nombre de la clase en la que se encuentra
} simbolo;

simbolo *tabla = NULL;
char contexto_actual[50] = "";
int contador_operaciones_coleccion = 0;

void insertar(simbolo **pT, simbolo *s) {
    s->sig = (*pT);
    (*pT) = s;
}

simbolo *buscar(simbolo *tabla, char nombre[20]) {
    while ((tabla != NULL) && (strcmp(nombre, tabla->nombre) != 0))
        tabla = tabla->sig;
    return tabla;
}
void imprimir_estadisticas(simbolo *tabla) {
    printf("\nEstadísticas por clase:\n");

    simbolo *temp = tabla;
    char clases[100][50];
    int conteo_clases = 0;

    while (temp) {
        int encontrado = 0;
        for (int i = 0; i < conteo_clases; i++) {
            if (strcmp(clases[i], temp->context) == 0) {
                encontrado = 1;
                break;
            }
        }
        if (!encontrado && strlen(temp->context) > 0) {
            strcpy(clases[conteo_clases++], temp->context);
        }
        temp = temp->sig;
    }

    printf("Clases con restricciones: %d\n\n", conteo_clases);

   for (int i = 0; i < conteo_clases; i++) {
        int invariantes = 0, operaciones = 0;
        temp = tabla;
        while (temp) {
            if (strcmp(temp->context, clases[i]) == 0) {
                if (temp->tipo == INV) invariantes++;
                if (temp->tipo == COLLECTION_OP) operaciones++;
            }
            temp = temp->sig;
        }
        printf("Clase: %s\n", clases[i]);
        printf("\tRestricciones: %d\n", invariantes);
        printf("\tOperaciones sobre colecciones: %d\n", operaciones);
    }
    printf("\nTotal de operaciones sobre colecciones: %d\n", contador_operaciones_coleccion);
}

void procesarToken(simbolo **tabla, char nombre[100], int tipo, int linea, int columna) {
    simbolo *nuevo = (simbolo *) malloc(sizeof(simbolo));
    strcpy(nuevo->nombre, nombre);
    nuevo->valor = (tipo == INT_LITERAL) ? atoi(nombre) : 0;
    nuevo->tipo = tipo;
    nuevo->linea = linea;
    nuevo->columna = columna;
    strcpy(nuevo->context, contexto_actual);
    insertar(tabla, nuevo);

    if (tipo == COLLECTION_OP) {
        contador_operaciones_coleccion++;
    }
    if (tipo == CONTEXT) {
        sscanf(yytext + 8, "%s", contexto_actual);
    }
}

#line 832 "lex.yy.c"
/* Expresiones Regulares OCL */
#line 834 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 122 "aLexico.l"

#line 124 "aLexico.l"
    /* Palabras Clave */
#line 1055 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 302 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 762 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 125 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, CONTEXT, yylineno, columna_actual); return CONTEXT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 126 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, INV, yylineno, columna_actual); return INV; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 127 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, PRE, yylineno, columna_actual); return PRE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 128 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, POST, yylineno, columna_actual); return POST; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 129 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, DEF, yylineno, columna_actual); return DEF; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 130 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, LET, yylineno, columna_actual); return LET; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 131 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, IN, yylineno, columna_actual); return IN; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 132 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, IF, yylineno, columna_actual); return IF; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 133 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, THEN, yylineno, columna_actual); return THEN; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 134 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, ELSE, yylineno, columna_actual); return ELSE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 135 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, ENDIF, yylineno, columna_actual); return ENDIF; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 136 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, SELF, yylineno, columna_actual); return SELF; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 137 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, RESULT, yylineno, columna_actual); return RESULT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 138 "aLexico.l"
{ columna_actual += yyleng; yylval.bval = 1; procesarToken(&tabla, yytext, BOOLEAN_LITERAL, yylineno, columna_actual); return BOOLEAN_LITERAL; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 139 "aLexico.l"
{ columna_actual += yyleng; yylval.bval = 0; procesarToken(&tabla, yytext, BOOLEAN_LITERAL, yylineno, columna_actual); return BOOLEAN_LITERAL; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 140 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, NULO, yylineno, columna_actual); return NULO; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 141 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, SET, yylineno, columna_actual); return SET; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 142 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, BAG, yylineno, columna_actual); return BAG; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 143 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, SEQUENCE, yylineno, columna_actual); return SEQUENCE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 144 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, COLLECTION, yylineno, columna_actual); return COLLECTION; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 145 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, INTEGER_TYPE, yylineno, columna_actual); return INTEGER_TYPE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 146 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, REAL_TYPE, yylineno, columna_actual); return REAL_TYPE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 147 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, BOOLEAN_TYPE, yylineno, columna_actual); return BOOLEAN_TYPE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 148 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, STRING_TYPE, yylineno, columna_actual); return STRING_TYPE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 149 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, OCLANY_TYPE, yylineno, columna_actual); return OCLANY_TYPE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 150 "aLexico.l"
{ columna_actual += yyleng; procesarToken(&tabla, yytext, OCLTYPE_TYPE, yylineno, columna_actual); return OCLTYPE_TYPE; }
	YY_BREAK
/* Operadores y Colecciones */
case 27:
YY_RULE_SETUP
#line 153 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual += yyleng; procesarToken(&tabla, yytext, COLLECTION_OP, yylineno, columna_actual); return COLLECTION_OP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 154 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual += yyleng; procesarToken(&tabla, yytext, LOGIC_OP, yylineno, columna_actual); return LOGIC_OP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 155 "aLexico.l"
{ columna_actual += yyleng; return NOT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 156 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual += yyleng; procesarToken(&tabla, yytext, ARITH_OP, yylineno, columna_actual); return ARITH_OP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 157 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual += yyleng; procesarToken(&tabla, yytext, REL_OP, yylineno, columna_actual); return REL_OP; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 161 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual += yyleng; procesarToken(&tabla, yytext, LOGIC_OP, yylineno, columna_actual); return LOGIC_OP; }
	YY_BREAK
/* Operadores Aritméticos */
case 33:
YY_RULE_SETUP
#line 164 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual++; procesarToken(&tabla, yytext, OPERATOR, yylineno, columna_actual); return PLUS; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 165 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual++; procesarToken(&tabla, yytext, OPERATOR, yylineno, columna_actual); return MINUS; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 166 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual++; procesarToken(&tabla, yytext, OPERATOR, yylineno, columna_actual); return MULT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 167 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual++; procesarToken(&tabla, yytext, OPERATOR, yylineno, columna_actual); return DIV; }
	YY_BREAK
/* Literales Numéricos */
case 37:
YY_RULE_SETUP
#line 172 "aLexico.l"
{ yylval.ival = atoi(yytext); columna_actual += yyleng; procesarToken(&tabla, yytext, INT_LITERAL, yylineno, columna_actual); return INT_LITERAL; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 174 "aLexico.l"
{
    char *text = strdup(yytext);
    for (int i = 0; text[i]; i++) if (text[i] == ',') text[i] = '.';
    yylval.dval = atof(text);
    free(text);
    columna_actual += yyleng;
    procesarToken(&tabla, yytext, REAL_LITERAL, yylineno, columna_actual);
    return REAL_LITERAL;
}
	YY_BREAK
/* Identificadores */
case 39:
YY_RULE_SETUP
#line 185 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual += yyleng; procesarToken(&tabla, yytext, ID, yylineno, columna_actual); return ID; }
	YY_BREAK
/* Literal de String */
case 40:
YY_RULE_SETUP
#line 189 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual += strlen(yytext); procesarToken(&tabla, yytext, STRING_LITERAL, yylineno, columna_actual); return STRING_LITERAL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 190 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual += strlen(yytext); procesarToken(&tabla, yytext, STRING_LITERAL, yylineno, columna_actual); return STRING_LITERAL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 191 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual += strlen(yytext); procesarToken(&tabla, yytext, STRING_LITERAL, yylineno, columna_actual); return STRING_LITERAL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 192 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual += strlen(yytext); procesarToken(&tabla, yytext, STRING_LITERAL, yylineno, columna_actual); return STRING_LITERAL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 193 "aLexico.l"
{ yylval.sval = safe_strdup(yytext); columna_actual += strlen(yytext); procesarToken(&tabla, yytext, STRING_LITERAL, yylineno, columna_actual); return STRING_LITERAL; }
	YY_BREAK
/* Símbolos OCL */
case 45:
YY_RULE_SETUP
#line 196 "aLexico.l"
{ columna_actual++; procesarToken(&tabla, yytext, DOT, yylineno, columna_actual); return DOT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 197 "aLexico.l"
{ columna_actual++; procesarToken(&tabla, yytext, COLON, yylineno, columna_actual); return COLON; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 198 "aLexico.l"
{ columna_actual += 2; procesarToken(&tabla, yytext, DCOLON, yylineno, columna_actual); return DCOLON; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 199 "aLexico.l"
{ columna_actual++; procesarToken(&tabla, yytext, COMA, yylineno, columna_actual); return COMA; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 200 "aLexico.l"
{ columna_actual++; procesarToken(&tabla, yytext, LPAREN, yylineno, columna_actual); return LPAREN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 201 "aLexico.l"
{ columna_actual++; procesarToken(&tabla, yytext, RPAREN, yylineno, columna_actual); return RPAREN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 202 "aLexico.l"
{ columna_actual++; procesarToken(&tabla, yytext, LBRACE, yylineno, columna_actual); return LBRACE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 203 "aLexico.l"
{ columna_actual++; procesarToken(&tabla, yytext, RBRACE, yylineno, columna_actual); return RBRACE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 204 "aLexico.l"
{ columna_actual++; procesarToken(&tabla, yytext, LBRACKET, yylineno, columna_actual); return LBRACKET; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 205 "aLexico.l"
{ columna_actual++; procesarToken(&tabla, yytext, RBRACKET, yylineno, columna_actual); return RBRACKET; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 206 "aLexico.l"
{ columna_actual++; procesarToken(&tabla, yytext, BARRA, yylineno, columna_actual); return BARRA; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 207 "aLexico.l"
{ columna_actual++; procesarToken(&tabla, yytext, AT_SIGN, yylineno, columna_actual); return AT_SIGN; }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 209 "aLexico.l"
{
    columna_actual = 1;
    yylineno++;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 214 "aLexico.l"
{ columna_actual += yyleng; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 216 "aLexico.l"
{ /* Ignorar comentarios */ }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 218 "aLexico.l"
{
    printf("Carácter no reconocido: '%s' en línea %d, columna %d\n", yytext, yylineno, columna_actual);
    columna_actual++;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 224 "aLexico.l"
ECHO;
	YY_BREAK
#line 1438 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 302 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 302 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 301);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 224 "aLexico.l"


int yywrap() {
    return 1;
}


