/**
 * @author mardedi
 * @author daniega
 */

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.entrega1.vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import uva.ipc.entrega1.modelo.Ruta1;
import java.util.Calendar;
import java.util.Date;
import java.awt.Color;

public class Vista extends javax.swing.JFrame {

    private Controlador miControlador;
    private DefaultListModel listModel = new DefaultListModel();
    /**
     * Constructor de la clase vista
     */
    public Vista() {
        initComponents();
        this.miControlador=new Controlador(this);
        trenesList.setModel(listModel);
        invisibilicecomponents();
        inicializarComboBoxes();
        fechaDateChooser.setMinSelectableDate(new Date());
    }
    
    
    /**
    *Funcion que permite obtener la fecha del dia actual
    */
    public Date getfecha() {   
        Date fecha = fechaDateChooser.getDate();
        return fecha;
    }
    
    public boolean horarioSemanal() {
        Calendar calendar = fechaDateChooser.getCalendar();
        int diaSemana = calendar.get(Calendar.DAY_OF_WEEK);

        // 1: Domingo, 2: Lunes, ..., 7: Sábado
        return diaSemana >= Calendar.MONDAY && diaSemana <= Calendar.FRIDAY;
    }

    /**
     * método get para el origen del viaje
     * @return origenSeleccionado - String
     */
    
    public String getOrigen() {
        String origenSeleccionado = (String) origenComboBox.getSelectedItem();
        return origenSeleccionado;
    }
    
    /**
     * método get para el destino del viaje
     * @return destinoSeleccionado - String
     */
    public String getDestino() {
        String destinoSeleccionado = (String) destinoComboBox.getSelectedItem();
        return destinoSeleccionado;
    }
    
    /**
     * método get para el pin escrito por el usuario
     * @return pin - String
     */
    
    public String getPin(){
        return pinTextField.getText();
    }

    /**
     * método get para obtener el precio asociado a un billete de tren
     * Se recorre la lista de rutas, y la que coincida se obtiene el valor asociado a su precio
     * @param trenes - lista de rutas
     * @return precio - double
     */
    
    public Double getPrecio(ArrayList<Ruta1> trenes) {
        double p=0.0;
        for (Ruta1 elem : trenes) {
            if(horarioSemanal()){
                if (elem.getEstacionOrigen().equals(getOrigen()) && elem.getEstacionDestino().equals(getDestino())) {
                    if(trenesList.getSelectedValue().substring(0, 5).trim().equals(elem.getIdRuta())){
                        p= elem.getPrecio();
                    }
                }
            }else{
                if (elem.getEstacionOrigen().equals(getOrigen()) && elem.getEstacionDestino().equals(getDestino())) {
                    if(trenesList.getSelectedValue().substring(0, 5).trim().equals(elem.getIdRuta())){
                        p= elem.getPrecio();
                    }
                }
            }
        }
        return p;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        intercambioButton = new javax.swing.JButton();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        origenComboBox = new javax.swing.JComboBox<>();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        destinoComboBox = new javax.swing.JComboBox<>();
        jPanel41 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        fechaLabel = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        fechaDateChooser = new com.toedter.calendar.JDateChooser();
        jPanel45 = new javax.swing.JPanel();
        error1Label = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        continuarButton = new javax.swing.JToggleButton();
        volver0Button = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        Paso2LabelText = new javax.swing.JLabel();
        jPanel59 = new javax.swing.JPanel();
        jPanel67 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel68 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        trenesList = new javax.swing.JList<>();
        jPanel52 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        jPanel65 = new javax.swing.JPanel();
        mascotaCheckBox = new javax.swing.JCheckBox();
        jPanel66 = new javax.swing.JPanel();
        biciCheckBox = new javax.swing.JCheckBox();
        jPanel61 = new javax.swing.JPanel();
        error2Label = new javax.swing.JLabel();
        jPanel62 = new javax.swing.JPanel();
        jPanel63 = new javax.swing.JPanel();
        volverButton = new javax.swing.JButton();
        jPanel64 = new javax.swing.JPanel();
        continuar2Button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        pinLabel = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        pinTextField = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        volver2Button = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        creditoButton = new javax.swing.JRadioButton();
        jPanel22 = new javax.swing.JPanel();
        emojiTarjetaTextField = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        labeltarjeta = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        usuarioButton = new javax.swing.JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        trainTextField = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        labeltren = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel74 = new javax.swing.JPanel();
        compraCompletadaLabel = new javax.swing.JLabel();
        jPanel75 = new javax.swing.JPanel();
        jPanel80 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detallesTrayectoTextArea = new javax.swing.JTextArea();
        jPanel76 = new javax.swing.JPanel();
        jPanel77 = new javax.swing.JPanel();
        comprarOtroButton = new javax.swing.JButton();
        jPanel78 = new javax.swing.JPanel();
        jPanel79 = new javax.swing.JPanel();
        salirButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame"); // NOI18N
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        jPanel26.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        jPanel26.add(jPanel32, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        jPanel26.add(jPanel33, java.awt.BorderLayout.LINE_END);

        jPanel34.setLayout(new java.awt.GridLayout(2, 0));

        jPanel35.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PASO 1");
        jPanel35.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel34.add(jPanel35);

        jPanel36.setLayout(new java.awt.GridLayout(2, 0));

        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SELECCIONE LAS");
        jPanel29.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel36.add(jPanel29);

        jPanel30.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CARACTERÍSTICAS DE SU VIAJE");
        jPanel30.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel36.add(jPanel30);

        jPanel34.add(jPanel36);

        jPanel26.add(jPanel34, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel26);

        jPanel27.setLayout(new java.awt.BorderLayout());

        jPanel31.setLayout(new java.awt.GridLayout(4, 2));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel31.add(jPanel42);

        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        intercambioButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        intercambioButton.setText("");
        intercambioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intercambioButtonActionPerformed(evt);
            }
        });
        jPanel43.add(intercambioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 40));

        jPanel31.add(jPanel43);

        jPanel27.add(jPanel31, java.awt.BorderLayout.LINE_END);

        jPanel37.setLayout(new java.awt.GridLayout(4, 0));

        jPanel38.setLayout(new java.awt.BorderLayout());

        origenComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione estación de origen" }));
        jPanel38.add(origenComboBox, java.awt.BorderLayout.CENTER);

        jPanel37.add(jPanel38);

        jPanel39.setLayout(new java.awt.BorderLayout());
        jPanel37.add(jPanel39);

        jPanel40.setLayout(new java.awt.BorderLayout());

        destinoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione estación de destino" }));
        jPanel40.add(destinoComboBox, java.awt.BorderLayout.CENTER);

        jPanel37.add(jPanel40);

        jPanel41.setLayout(new java.awt.BorderLayout());
        jPanel37.add(jPanel41);

        jPanel27.add(jPanel37, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel27);

        jPanel28.setLayout(new java.awt.GridLayout(3, 0));

        jPanel44.setLayout(new java.awt.BorderLayout());

        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaLabel.setText("Fecha:");
        jPanel47.add(fechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, -1));

        jPanel44.add(jPanel47, java.awt.BorderLayout.LINE_START);

        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("");
        jPanel48.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 30));

        jPanel44.add(jPanel48, java.awt.BorderLayout.LINE_END);

        jPanel49.setLayout(new java.awt.BorderLayout());

        fechaDateChooser.setFocusable(false);
        fechaDateChooser.setMaxSelectableDate(new java.util.Date(253370764883000L));
        jPanel49.add(fechaDateChooser, java.awt.BorderLayout.CENTER);

        jPanel44.add(jPanel49, java.awt.BorderLayout.CENTER);

        jPanel28.add(jPanel44);

        jPanel45.setLayout(new java.awt.BorderLayout());

        error1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel45.add(error1Label, java.awt.BorderLayout.CENTER);

        jPanel28.add(jPanel45);

        continuarButton.setText("Continuar");

        volver0Button.setText("Volver");
        volver0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver0ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addComponent(continuarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volver0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(continuarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addComponent(volver0Button, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
        );

        jPanel28.add(jPanel46);

        jPanel1.add(jPanel28);

        getContentPane().add(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel2.setLayout(new java.awt.GridLayout(3, 0));

        jPanel50.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        jPanel50.add(jPanel53, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        jPanel50.add(jPanel54, java.awt.BorderLayout.LINE_END);

        jPanel55.setLayout(new java.awt.BorderLayout());

        jPanel56.setLayout(new java.awt.BorderLayout());
        jPanel55.add(jPanel56, java.awt.BorderLayout.PAGE_START);

        jPanel57.setLayout(new java.awt.GridLayout(2, 0));

        jPanel58.setLayout(new java.awt.BorderLayout());

        Paso2LabelText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Paso2LabelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Paso2LabelText.setText("PASO 2");
        jPanel58.add(Paso2LabelText, java.awt.BorderLayout.CENTER);

        jPanel57.add(jPanel58);

        jPanel59.setLayout(new java.awt.GridLayout(2, 0));

        jPanel67.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SELECCIONE SU HORARIO");
        jPanel67.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel59.add(jPanel67);

        jPanel68.setLayout(new java.awt.BorderLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Y EL RESTO DE PREFERENCIAS");
        jPanel68.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel59.add(jPanel68);

        jPanel57.add(jPanel59);

        jPanel55.add(jPanel57, java.awt.BorderLayout.CENTER);

        jPanel50.add(jPanel55, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel50);

        jPanel51.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setViewportView(trenesList);

        jPanel51.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel51);

        jPanel52.setLayout(new java.awt.GridLayout(3, 0));

        jPanel60.setLayout(new java.awt.GridLayout(1, 2));

        jPanel65.setLayout(new java.awt.BorderLayout());

        mascotaCheckBox.setText("Mascota");
        mascotaCheckBox.setEnabled(false);
        mascotaCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel65.add(mascotaCheckBox, java.awt.BorderLayout.CENTER);

        jPanel60.add(jPanel65);

        jPanel66.setLayout(new java.awt.BorderLayout());

        biciCheckBox.setText("Bicicleta");
        biciCheckBox.setEnabled(false);
        biciCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel66.add(biciCheckBox, java.awt.BorderLayout.CENTER);

        jPanel60.add(jPanel66);

        jPanel52.add(jPanel60);

        jPanel61.setLayout(new java.awt.BorderLayout());

        error2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel61.add(error2Label, java.awt.BorderLayout.CENTER);

        jPanel52.add(jPanel61);

        jPanel62.setLayout(new java.awt.GridLayout(1, 2));

        jPanel63.setLayout(new java.awt.BorderLayout());

        volverButton.setText("Volver");
        volverButton.setEnabled(false);
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        jPanel63.add(volverButton, java.awt.BorderLayout.CENTER);

        jPanel62.add(jPanel63);

        jPanel64.setLayout(new java.awt.BorderLayout());

        continuar2Button.setText("Continuar");
        continuar2Button.setEnabled(false);
        continuar2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuar2ButtonActionPerformed(evt);
            }
        });
        jPanel64.add(continuar2Button, java.awt.BorderLayout.CENTER);

        jPanel62.add(jPanel64);

        jPanel52.add(jPanel62);

        jPanel2.add(jPanel52);

        getContentPane().add(jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setMinimumSize(new java.awt.Dimension(36, 128));
        jPanel6.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10, java.awt.BorderLayout.LINE_START);

        jPanel11.setLayout(new java.awt.GridLayout(2, 0));

        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASO 3");
        jPanel18.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel18);

        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ELIJA SU MÉTODO DE PAGO");
        jPanel19.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel19);

        jPanel6.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        jPanel20.setEnabled(false);
        jPanel20.setLayout(new java.awt.GridLayout(1, 2));

        pinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pinLabel.setText("Introduzca el PIN");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(pinLabel)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(pinLabel)
                .addGap(16, 16, 16))
        );

        jPanel20.add(jPanel24);

        pinTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinTextField.setEnabled(false);
        pinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel20.add(jPanel25);

        jPanel7.add(jPanel20);

        jPanel23.setLayout(new java.awt.BorderLayout());

        volver2Button.setText("Volver");
        volver2Button.setEnabled(false);
        volver2Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        volver2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver2ButtonActionPerformed(evt);
            }
        });
        jPanel23.add(volver2Button, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel23);

        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        jPanel12.setLayout(new java.awt.GridLayout(3, 0));

        jPanel21.setLayout(new java.awt.BorderLayout());

        buttonGroup1.add(creditoButton);
        creditoButton.setText("Tarjeta de Credito");
        creditoButton.setEnabled(false);
        creditoButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditoButton.setMaximumSize(new java.awt.Dimension(119, 10));
        creditoButton.setMinimumSize(new java.awt.Dimension(119, 10));
        creditoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditoButtonActionPerformed(evt);
            }
        });
        jPanel21.add(creditoButton, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel21);

        jPanel22.setLayout(new java.awt.BorderLayout());

        emojiTarjetaTextField.setEditable(false);
        emojiTarjetaTextField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 64)); // NOI18N
        emojiTarjetaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emojiTarjetaTextField.setText("💳");
        emojiTarjetaTextField.setEnabled(false);
        emojiTarjetaTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emojiTarjetaTextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emojiTarjetaTextFieldMouseExited(evt);
            }
        });
        jPanel22.add(emojiTarjetaTextField, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel22);

        jPanel14.setLayout(new java.awt.BorderLayout());

        labeltarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeltarjeta.setText("Mantenga la tarjeta aqui 2 segundos");
        labeltarjeta.setEnabled(false);
        jPanel14.add(labeltarjeta, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel14);

        jPanel8.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridLayout(3, 0));

        jPanel15.setLayout(new java.awt.BorderLayout());

        buttonGroup1.add(usuarioButton);
        usuarioButton.setText("Tarjeta Usuario TCyL");
        usuarioButton.setEnabled(false);
        usuarioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioButtonActionPerformed(evt);
            }
        });
        jPanel15.add(usuarioButton, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel15);

        jPanel16.setLayout(new java.awt.BorderLayout());

        trainTextField.setEditable(false);
        trainTextField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 64)); // NOI18N
        trainTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        trainTextField.setText("🚂");
        trainTextField.setEnabled(false);
        trainTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trainTextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trainTextFieldMouseExited(evt);
            }
        });
        jPanel16.add(trainTextField, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel16);

        jPanel17.setLayout(new java.awt.BorderLayout());

        labeltren.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeltren.setText("Mantenga la tarjeta aqui 2 segundos");
        labeltren.setEnabled(false);
        jPanel17.add(labeltren, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel17);

        jPanel8.add(jPanel13);

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel4.setLayout(new java.awt.GridLayout(3, 0));

        jPanel74.setLayout(new java.awt.BorderLayout());

        compraCompletadaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        compraCompletadaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compraCompletadaLabel.setText("COMPRA COMPLETADA");
        jPanel74.add(compraCompletadaLabel, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel74);

        jPanel75.setLayout(new java.awt.GridLayout(1, 2));

        jPanel80.setLayout(new java.awt.BorderLayout());

        detallesTrayectoTextArea.setEditable(false);
        detallesTrayectoTextArea.setColumns(20);
        detallesTrayectoTextArea.setRows(5);
        jScrollPane2.setViewportView(detallesTrayectoTextArea);

        jPanel80.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel75.add(jPanel80);

        jPanel4.add(jPanel75);

        jPanel76.setLayout(new java.awt.GridLayout(3, 0));

        jPanel77.setLayout(new java.awt.BorderLayout());

        comprarOtroButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comprarOtroButton.setText("COMPRAR OTRO TICKET");
        comprarOtroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarOtroButtonActionPerformed(evt);
            }
        });
        jPanel77.add(comprarOtroButton, java.awt.BorderLayout.CENTER);

        jPanel76.add(jPanel77);

        javax.swing.GroupLayout jPanel78Layout = new javax.swing.GroupLayout(jPanel78);
        jPanel78.setLayout(jPanel78Layout);
        jPanel78Layout.setHorizontalGroup(
            jPanel78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel78Layout.setVerticalGroup(
            jPanel78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jPanel76.add(jPanel78);

        jPanel79.setLayout(new java.awt.BorderLayout());

        salirButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salirButton.setText("SALIR");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        jPanel79.add(salirButton, java.awt.BorderLayout.CENTER);

        jPanel76.add(jPanel79);

        jPanel4.add(jPanel76);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * permite el intercambio entre las combobox de origen y destino
     * @param evt - pulsar el intercambioButton
     */
    
    private void intercambioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intercambioButtonActionPerformed
        String origen = getOrigen();
        String destino = getDestino();
        destinoComboBox.setSelectedItem(origen);
        origenComboBox.setSelectedItem(destino);    
    }//GEN-LAST:event_intercambioButtonActionPerformed

   
    /**
     * Permite obtener la lista de trenes coincidentes con las especificaciones del usuario en el paso 1
     * @param trenes 
     */
    
    public void actualizarTrenes(ArrayList<Ruta1> trenes) {
        listModel.clear();
        for (Ruta1 elem : trenes) {
            if(horarioSemanal()){
                if (elem.getEstacionOrigen().equals(getOrigen()) && elem.getEstacionDestino().equals(getDestino())) {
                    for (String horario : elem.getHorariosSemana()) {
                        listModel.addElement(elem.getIdRuta() + " " + elem.getTiempo() + " " + elem.getPrecio() + "€  " + horario);
                        }
                }
            }else{
                if (elem.getEstacionOrigen().equals(getOrigen()) && elem.getEstacionDestino().equals(getDestino())) {
                    for (String horario : elem.getHorariosFinDeSemana()) {
                        listModel.addElement(elem.getIdRuta() + " " + elem.getTiempo() + " " + elem.getPrecio() + "€  " + horario);
                        }
                }
            }
        }
        trenesList.setModel(listModel);
    }
    
    /**
     * Permite pasar del paso 2 al 3, invisibilizando el 2 y poniendo en visible el 3
     * @param evt - presionar el continuar2Button
     */
    
    private void continuar2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuar2ButtonActionPerformed
        if (!trenesList.isSelectionEmpty()) {
            jPanel2.setVisible(false);
            jPanel3.setVisible(true);
            usuarioButton.setEnabled(true);
            creditoButton.setEnabled(true);
            pinTextField.setEnabled(false);
            volver2Button.setEnabled(true);
            trainTextField.setVisible(true);
            emojiTarjetaTextField.setVisible(true);
            pinLabel.setVisible(false);
            error2Label.setEnabled(false);
            error2Label.setVisible(false);
        }else{
            error2Label.setForeground(Color.red);
            error2Label.setText(miControlador.getSegundoPasoError());
        
        }
    }//GEN-LAST:event_continuar2ButtonActionPerformed

    /**
     * Permite volver del paso 2 al 1 en caso de que el usuario se equivocara, invisibilizando el paso 2
     * y poniendo en visible el 3
     * @param evt - presionar el volverButton
     */
    
    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        usuarioButton.setEnabled(false);
        creditoButton.setEnabled(false);
        
    }//GEN-LAST:event_volverButtonActionPerformed
    
    /**
     * Permite pagar con la tarjeta de usuario de TCyL
     * @param evt - presionar usuarioButton
     */
    
    private void usuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioButtonActionPerformed
        trainTextField.setEnabled(true);
        labeltren.setEnabled(true);
        labeltren.setVisible(true);
        emojiTarjetaTextField.setEnabled(false);
        labeltarjeta.setVisible(false);
        jPanel20.setEnabled(false);
        jPanel20.setVisible(false);
    }//GEN-LAST:event_usuarioButtonActionPerformed

    /**
     * Permite pagar con la tarjeta de crédito
     * @param evt - presionar creditoButton
     */
    
    private void creditoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditoButtonActionPerformed
        trainTextField.setEnabled(false);
        labeltarjeta.setEnabled(true);
        labeltren.setVisible(false);
        emojiTarjetaTextField.setEnabled(true);
        labeltarjeta.setVisible(true);
        jPanel20.setEnabled(true);
        jPanel20.setVisible(true);
    }//GEN-LAST:event_creditoButtonActionPerformed

    /**
     * Permite volver del paso 3 al paso 2, invisibilizando el paso 3 y poniendo visible el paso 2
     * @param evt 
     */
    
    private void volver2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver2ButtonActionPerformed
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
        emojiTarjetaTextField.setEnabled(false);
    }//GEN-LAST:event_volver2ButtonActionPerformed

    /**
     * Simula un pago con tarjeta contactless.
     * @param evt - el raton entra en el emojiTarjetaTextField
     */
    
    private void emojiTarjetaTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojiTarjetaTextFieldMouseEntered
        if(emojiTarjetaTextField.isEnabled()){
            miControlador.procesarEventoTimer();
        }
    }//GEN-LAST:event_emojiTarjetaTextFieldMouseEntered

    /**
     * Simula que la tarjeta se retira del pago contactless.
     * @param evt - el raton sale del emojiTarjetaTextField
     */
    
    private void emojiTarjetaTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojiTarjetaTextFieldMouseExited
        if(emojiTarjetaTextField.isEnabled()){
            miControlador.procesarEventoTimerEnd();
        }
    }//GEN-LAST:event_emojiTarjetaTextFieldMouseExited

    /**
     * Permite cambiar el mensaje de debajo de el textfield correspondiente a cada tarjeta dependiendo
     * de cual sea la opcion de pago habilitada
     * @param mensaje - Text que se quiere proporcinar al label
     */
    
    public void cambiomensajetarjeta(String mensaje){
        if(emojiTarjetaTextField.isEnabled()){
            labeltarjeta.setText(mensaje);
            labeltarjeta.setForeground(Color.red);
        }
        else if(trainTextField.isEnabled()){
            labeltarjeta.setText(mensaje);
            labeltren.setText(mensaje);
            labeltren.setForeground(Color.red);
        }
    }
    
    /**
     * Devuelve si es la opcion de pago con tarjeta bancaria la que esta activada
     * @return 
     */
    
    public boolean gettarjetaTextFieldState(){
        return emojiTarjetaTextField.isEnabled();
    }
    
    /**
     * Permite que el usuario ponga el PIN de la tarjeta una vez que el proceso
     * de contactless ha terminado
     */
    
    public void tarjetaAceptada(){
        pinLabel.setVisible(true);
        pinTextField.setVisible(true);
        pinTextField.setEnabled(true);
    }
    
    /**
     * Permite cambiar el mensaje del label del pin en caso de que el usuario introduzca uno incorrecto
     */
    
    public void errorContrasena(){
        pinLabel.setText("PIN INCORRECTO");
        pinLabel.setForeground(Color.red);
    }
    
    /**
     * Permite comprobar si el pin es correcto o no
     * @param evt - el usuario presiona enter una vez que ha escrito el pin
     */
    
    private void pinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinTextFieldActionPerformed
        miControlador.comprobarPinTarjeta(pinTextField.getText());
    }//GEN-LAST:event_pinTextFieldActionPerformed

    /**
     * Permite pasar al paso 4 en caso de que la tarjeta hay sido aceptada
     * Invisibiliza el paso 3 y pone en visible el paso 4
     */
    
    public void tarjetaAceptadaPin(){
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        salirButton.setVisible(true);
        comprarOtroButton.setVisible(true);
        detallesTrayectoTextArea.setVisible(true);
        rellenarDetalles();
    }
    
    /**
     * Rellena en el detallesTrayectoTextArea los detalles respecto al viaje que el usuario acaba de adquirir
     */
    
    public void rellenarDetalles(){
       detallesTrayectoTextArea.setText("");
       detallesTrayectoTextArea.append("DETALLES DE SU TRAYECTO\n");
       detallesTrayectoTextArea.append("Origen: ");
       detallesTrayectoTextArea.append(origenComboBox.getSelectedItem().toString());
       detallesTrayectoTextArea.append("\nDestino: ");
       detallesTrayectoTextArea.append(destinoComboBox.getSelectedItem().toString());
       detallesTrayectoTextArea.append("\nMascota: ");
       if(mascotaCheckBox.isSelected()){
           detallesTrayectoTextArea.append("SI");
       }
       else{
           detallesTrayectoTextArea.append("NO");
       }
       detallesTrayectoTextArea.append("\nBicicleta: ");
       if(biciCheckBox.isSelected()){
           detallesTrayectoTextArea.append("SI");
       }
       else{
           detallesTrayectoTextArea.append("NO");
       }
    }
    
    /**
     * Simula un pago con la tarjeta TCyL contactless.
     * @param evt - el raton entra en el trainTextField
     */
    
    private void trainTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainTextFieldMouseEntered
        if(trainTextField.isEnabled()){
            miControlador.procesarEventoTimer();
        }
    }//GEN-LAST:event_trainTextFieldMouseEntered

    /**
     * Simula que la tarjeta TCyL se retira del pago contactless.
     * @param evt - el raton sale del trainTextField
     */
    
    private void trainTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainTextFieldMouseExited
        if(trainTextField.isEnabled()){
            miControlador.procesarEventoTimerEnd();
        }
    }//GEN-LAST:event_trainTextFieldMouseExited
  
    /**
     * Permite al usuario recomenzar el proceso de compra en caso de que quiera comprar otro billete
     * @param evt - Presionar el comprarOtroButton
     */
    
    private void comprarOtroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarOtroButtonActionPerformed
        jPanel4.setVisible(false);
        jPanel1.setVisible(true);
        invisibilicecomponents();
        resetearelementos();
    }//GEN-LAST:event_comprarOtroButtonActionPerformed

    /**
     * Permite salir de la aplicación
     * @param evt - presionar el salirButton
     */
    
    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirButtonActionPerformed

    private void volver0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver0ButtonActionPerformed
        VistaInicial newframe = new VistaInicial();
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_volver0ButtonActionPerformed

    /**
     * Invisibiliza componentes antes de comenzar el programa para evitar
     * que el usuario pueda acceder a ellas antes de lo debido
     */
    
    private void invisibilicecomponents(){
        trainTextField.setVisible(false);
        emojiTarjetaTextField.setVisible(false);
        pinLabel.setVisible(false);
        pinTextField.setVisible(false);
        labeltarjeta.setVisible(false);
        labeltren.setVisible(false);
        salirButton.setVisible(false);
        comprarOtroButton.setVisible(false);
        detallesTrayectoTextArea.setVisible(false);
    }
    
    /**
     * Resetea ciertos elementos que guardan su estado despues de que 
     * el usuario decida que quiere comprar otro billete
     */
    
    private void resetearelementos(){
        origenComboBox.setSelectedIndex(0);
        destinoComboBox.setSelectedIndex(0);
        fechaDateChooser.setDate(null);
        mascotaCheckBox.setSelected(false);
        biciCheckBox.setSelected(false);
        buttonGroup1.clearSelection();
        emojiTarjetaTextField.setEnabled(false);
        trainTextField.setEnabled(false);
        pinTextField.setVisible(false);
        pinTextField.setEnabled(true);
        pinTextField.setText("");
    }
    
    /**
     * Inicializa los valores de las ComboBoxes dependiendo de los lugares de origen y destino
     */
    
    private void inicializarComboBoxes() {    
        for (String estacion : miControlador.getEstaciones()) {
            origenComboBox.addItem(estacion);
            destinoComboBox.addItem(estacion);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Paso2LabelText;
    private javax.swing.JCheckBox biciCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel compraCompletadaLabel;
    private javax.swing.JButton comprarOtroButton;
    private javax.swing.JButton continuar2Button;
    private javax.swing.JToggleButton continuarButton;
    private javax.swing.JRadioButton creditoButton;
    private javax.swing.JComboBox<String> destinoComboBox;
    private javax.swing.JTextArea detallesTrayectoTextArea;
    private javax.swing.JTextField emojiTarjetaTextField;
    private javax.swing.JLabel error1Label;
    private javax.swing.JLabel error2Label;
    private com.toedter.calendar.JDateChooser fechaDateChooser;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JButton intercambioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labeltarjeta;
    private javax.swing.JLabel labeltren;
    private javax.swing.JCheckBox mascotaCheckBox;
    private javax.swing.JComboBox<String> origenComboBox;
    private javax.swing.JLabel pinLabel;
    private javax.swing.JTextField pinTextField;
    private javax.swing.JButton salirButton;
    private javax.swing.JTextField trainTextField;
    private javax.swing.JList<String> trenesList;
    private javax.swing.JRadioButton usuarioButton;
    private javax.swing.JToggleButton volver0Button;
    private javax.swing.JButton volver2Button;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables

    
}
