/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.entrega2.vista;

import java.awt.Color;


/**
 * @author mardedi
 * @author daniega
 */

public class VistaRecargaTarjeta extends javax.swing.JFrame {
    
    private ControladorRecargaTarjeta miControlador;
    private int cantidadSumar=0;

    /**
     * Creates new form VistaRecargaTarjeta
     */
    public VistaRecargaTarjeta() {
        initComponents();
        reiniciarcomponentes();
        this.miControlador=new ControladorRecargaTarjeta(this);
        miControlador.iniciarSaldo();
    }   
    
    /**
    * Muestra un mensaje de error en la vista cuando se ingresa un PIN incorrecto.
    * Limpia el campo de texto del PIN, establece un mensaje de "PIN INCORRECTO" en la etiqueta correspondiente
    * y cambia el color del mensaje a rojo.
    */
    
    public void errorContrasena(){
        pinTextField.setText("");
        pinLabel.setText("PIN INCORRECTO");
        pinLabel.setForeground(Color.red);
    }

    /**
    * Establece el saldo actual en el campo de texto de la vista.
    * El saldo se formatea como un valor decimal con dos dígitos decimales y se concatena con el símbolo de euro.
    *
    * @param saldo El saldo a ser mostrado en la vista.
    */
    
    public void setTextSaldo(double saldo){
        java.text.DecimalFormat formatodecimal = new java.text.DecimalFormat("#.##");
        String numerodecimal = formatodecimal.format(saldo);
        numerodecimal = numerodecimal+"€";
        saldoActualTextField.setText(numerodecimal);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        saldoActualLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        saldoActualTextField = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        diezButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        veinteButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        cincuentaButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        mantenerLabel = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        emojiTarjetaTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        pinLabel = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        enterLabel = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        pinTextField = new javax.swing.JPasswordField();
        jPanel25 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        volverButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 575));
        setPreferredSize(new java.awt.Dimension(400, 575));

        jPanel1.setLayout(new java.awt.GridLayout(5, 0));

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel8.setLayout(new java.awt.BorderLayout());

        saldoActualLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldoActualLabel.setText("SALDO ACTUAL DE LA TARJETA");
        jPanel8.add(saldoActualLabel, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(3, 0));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel20);

        jPanel21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel21.setLayout(new java.awt.BorderLayout());

        saldoActualTextField.setEditable(false);
        saldoActualTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel21.add(saldoActualTextField, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel21);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel22);

        jPanel3.add(jPanel9);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 3));

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel10.setLayout(new java.awt.BorderLayout());

        diezButton.setText("10€");
        diezButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diezButtonActionPerformed(evt);
            }
        });
        jPanel10.add(diezButton, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel11.setLayout(new java.awt.BorderLayout());

        veinteButton.setText("20€");
        veinteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veinteButtonActionPerformed(evt);
            }
        });
        jPanel11.add(veinteButton, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel12.setLayout(new java.awt.BorderLayout());

        cincuentaButton.setText("50€");
        cincuentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincuentaButtonActionPerformed(evt);
            }
        });
        jPanel12.add(cincuentaButton, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel12);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel14.setLayout(new java.awt.BorderLayout());

        mantenerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mantenerLabel.setText("MANTENGA SU TARJETA AQUÍ 2 SEGUNDOS");
        jPanel14.add(mantenerLabel, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        jPanel13.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel15, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel16, java.awt.BorderLayout.LINE_END);

        jPanel17.setLayout(new java.awt.BorderLayout());

        emojiTarjetaTextField.setEditable(false);
        emojiTarjetaTextField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 64)); // NOI18N
        emojiTarjetaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emojiTarjetaTextField.setText("💳");
        emojiTarjetaTextField.setEnabled(false);
        emojiTarjetaTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emojiTarjetaTextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emojiTarjetaTextFieldMouseExited(evt);
            }
        });
        jPanel17.add(emojiTarjetaTextField, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jPanel18.setLayout(new java.awt.GridLayout(2, 0));

        jPanel27.setLayout(new java.awt.BorderLayout());

        pinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pinLabel.setText("INTRODUZCA SU PIN");
        jPanel27.add(pinLabel, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel27);

        jPanel26.setLayout(new java.awt.BorderLayout());

        enterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterLabel.setText("PULSE ENTER PARA PROCESAR EL PIN");
        jPanel26.add(enterLabel, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel26);

        jPanel6.add(jPanel18);

        jPanel19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel19.setLayout(new java.awt.GridLayout(3, 0));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel19.add(jPanel23);

        jPanel24.setLayout(new java.awt.BorderLayout());

        pinTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinTextFieldActionPerformed(evt);
            }
        });
        jPanel24.add(pinTextField, java.awt.BorderLayout.CENTER);

        jPanel19.add(jPanel24);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel19.add(jPanel25);

        jPanel6.add(jPanel19);

        jPanel1.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 10, 10));
        jPanel7.setLayout(new java.awt.BorderLayout());

        volverButton.setText("VOLVER");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        jPanel7.add(volverButton, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RECARGAR TARJETA");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Método llamado cuando el cursor del ratón entra en el área del campo de texto de emojiTarjetaTextField.
    * Si el campo de texto está habilitado, activa el evento de temporizador en el controlador.
    *
    * @param evt El evento del mouse que desencadena esta acción.
    */
    
    private void emojiTarjetaTextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojiTarjetaTextFieldMouseEntered
        if(emojiTarjetaTextField.isEnabled()){
            miControlador.procesarEventoTimer();
        }
    }//GEN-LAST:event_emojiTarjetaTextFieldMouseEntered

    /**
    * Método llamado cuando el cursor del ratón sale del área del campo de texto de emojiTarjetaTextField.
    * Si el campo de texto está habilitado, activa el evento de finalización de temporizador en el controlador.
    *
    * @param evt El evento del mouse que desencadena esta acción.
    */
    
    private void emojiTarjetaTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emojiTarjetaTextFieldMouseExited
        if(emojiTarjetaTextField.isEnabled()){
            miControlador.procesarEventoTimerEnd();
        }
    }//GEN-LAST:event_emojiTarjetaTextFieldMouseExited
    
    /**
    * Método llamado cuando se presiona la tecla "Enter" en el campo de texto del PIN.
    * Obtiene el texto ingresado en el campo de contraseña y llama al controlador para verificar el PIN de la tarjeta.
    *
    * @param evt El evento de acción que desencadena esta acción.
    */
    
    private void pinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinTextFieldActionPerformed
        String Pass = new String(pinTextField.getPassword());
        miControlador.comprobarPinTarjeta(Pass);
    }//GEN-LAST:event_pinTextFieldActionPerformed

    /**
    * Método llamado cuando se presiona el botón "10" para recargar la tarjeta.
    * Reinicia el estado de todos los botones de recarga y establece el color de fondo del botón "10" en blanco.
    * Llama al método para mostrar la tarjeta.
    *
    * @param evt El evento de acción que desencadena esta acción.
    */
    
    private void diezButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diezButtonActionPerformed
        iniciarbotones();
        diezButton.setBackground(Color.white);
        visibilizarTarjeta();
    }//GEN-LAST:event_diezButtonActionPerformed

    /**
    * Método llamado cuando se presiona el botón "20" para recargar la tarjeta.
    * Reinicia el estado de todos los botones de recarga y establece el color de fondo del botón "20" en blanco.
    * Llama al método para mostrar la tarjeta.
    *
    * @param evt El evento de acción que desencadena esta acción.
    */
    
    private void veinteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veinteButtonActionPerformed
        iniciarbotones();
        veinteButton.setBackground(Color.white);
        visibilizarTarjeta();
    }//GEN-LAST:event_veinteButtonActionPerformed

    /**
    * Método llamado cuando se presiona el botón "50" para recargar la tarjeta.
    * Reinicia el estado de todos los botones de recarga y establece el color de fondo del botón "50" en blanco.
    * Llama al método para mostrar la tarjeta.
    *
    * @param evt El evento de acción que desencadena esta acción.
    */
    
    private void cincuentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincuentaButtonActionPerformed
        iniciarbotones();
        cincuentaButton.setBackground(Color.white);
        visibilizarTarjeta();
    }//GEN-LAST:event_cincuentaButtonActionPerformed

    /**
    * Método llamado cuando se presiona el botón "Volver".
    * Llama al controlador para procesar el evento de volver.
    *
    * @param evt El evento de acción que desencadena esta acción.
    */
    
    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        miControlador.VolverButtonEvento();
    }//GEN-LAST:event_volverButtonActionPerformed
    
    /**
    * Restablece el estado de los botones de recarga.
    */
    
    private void iniciarbotones(){
        diezButton.setBackground(Color.LIGHT_GRAY);
        veinteButton.setBackground(Color.LIGHT_GRAY);
        cincuentaButton.setBackground(Color.LIGHT_GRAY);
    }
    
    /**
    * Obtiene el valor de recarga seleccionado por el usuario.
    *
    * @return El valor de recarga seleccionado (10, 20 o 50).
    */
    
    public int getRecarga(){
        if(diezButton.getBackground().equals(Color.white)){
            return 10;
        }
        if(veinteButton.getBackground().equals(Color.white)){
            return 20;
        }
        if(cincuentaButton.getBackground().equals(Color.white)){
            return 50;
        }
        else{
            return 0;
        }
    }
    
    /**
    * Cambia el mensaje de la tarjeta mostrado en la vista.
    *
    * @param mensaje El mensaje a ser mostrado.
    * @param color El color del mensaje.
    */
    
    public void cambioMensajeTarjeta(String mensaje,Color color){
        mantenerLabel.setForeground(color);
        mantenerLabel.setText(mensaje);
    }
    
    /**
    * Muestra el campo de PIN y la etiqueta de la tarjeta en la vista.
    */
    
    public void mostrarPIN(){
        enterLabel.setVisible(true);
        pinLabel.setVisible(true);
        pinTextField.setVisible(true);
        pinTextField.setEnabled(true);
    }
    
    /**
    * Muestra la etiqueta y el campo de texto de la tarjeta en la vista.
    */
    
    private void visibilizarTarjeta(){
        mantenerLabel.setVisible(true);
        emojiTarjetaTextField.setVisible(true);
        emojiTarjetaTextField.setEnabled(true);
    }
    
    /**
    * Reinicia el estado de todos los componentes relacionados con la tarjeta en la vista.
    */
    
    private void reiniciarcomponentes(){
        enterLabel.setVisible(false);
        pinLabel.setVisible(false);
        pinTextField.setVisible(false);
        pinTextField.setEnabled(false);
        cambioMensajeTarjeta("MANTENGA SU TARJETA AQUÍ 2 SEGUNDOS",Color.BLACK);
        pinLabel.setText("INTRODUZCA SU PIN");
        pinLabel.setForeground(Color.BLACK);
        mantenerLabel.setVisible(false);
        emojiTarjetaTextField.setVisible(false);
        emojiTarjetaTextField.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cincuentaButton;
    private javax.swing.JButton diezButton;
    private javax.swing.JTextField emojiTarjetaTextField;
    private javax.swing.JLabel enterLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel mantenerLabel;
    private javax.swing.JLabel pinLabel;
    private javax.swing.JPasswordField pinTextField;
    private javax.swing.JLabel saldoActualLabel;
    private javax.swing.JTextField saldoActualTextField;
    private javax.swing.JButton veinteButton;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables

}
