/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author mardedi
 * @author daniega
 */
package uva.ipc.entrega2.vista;

/**
 * Clase vista que muestra la vista inicial
 * @author danig
 */

public class VistaInicial extends javax.swing.JFrame {

    private ControladorInicial miControlador;
    
    /**
     * Creates new form VistaInicial
     */
    public VistaInicial() {
        initComponents();
        this.miControlador=new ControladorInicial(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        comprarBilleteButton = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        accesoTarjetaButton = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        seleccioneOpcionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 200));

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 130));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 5));
        jPanel6.setLayout(new java.awt.BorderLayout());

        comprarBilleteButton.setText("COMPRAR BILLETE");
        comprarBilleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBilleteButtonActionPerformed(evt);
            }
        });
        jPanel6.add(comprarBilleteButton, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel7.setLayout(new java.awt.BorderLayout());

        accesoTarjetaButton.setText("ACCESO CON TARJETA");
        accesoTarjetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesoTarjetaButtonActionPerformed(evt);
            }
        });
        jPanel7.add(accesoTarjetaButton, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        seleccioneOpcionLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        seleccioneOpcionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccioneOpcionLabel.setText("SELECCIONE UNA OPCIÓN");
        seleccioneOpcionLabel.setToolTipText("");
        jPanel2.add(seleccioneOpcionLabel, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Método que llama al método asociado de la clase ControladorInicial
     * para cambiar de vista (Vista.class)
     * @param evt 
     */
    
    private void comprarBilleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBilleteButtonActionPerformed
        miControlador.procesarEventoComprarBilleteButton();
    }//GEN-LAST:event_comprarBilleteButtonActionPerformed
 
    /**
     * Método que llama al método asociado de la clase ControladorInicial
     * para cambiar de vista (VistaTarjeta.class)
     * @param evt 
     */
    
    private void accesoTarjetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoTarjetaButtonActionPerformed
        miControlador.procesarEventoAccesoConTarjetaButton();
    }//GEN-LAST:event_accesoTarjetaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton accesoTarjetaButton;
    private javax.swing.JToggleButton comprarBilleteButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel seleccioneOpcionLabel;
    // End of variables declaration//GEN-END:variables

}