/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.entrega2.vista;


/**
 * @author mardedi
 * @author daniega
 */

public class VistaTarjeta extends javax.swing.JFrame {
    
    private ControladorTarjeta miControlador;
    /**
     * Creates new form VistaTarjeta
     */
    public VistaTarjeta() {
        initComponents();
        this.miControlador=new ControladorTarjeta(this);
        miControlador.añadirbilletes();
        billetesCompradosTextField.setText(miControlador.iniciarNumBiletes());
        miControlador.iniciarSaldo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        billetesCompradosLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        billetesCompradosTextField = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        saldoLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        saldoTextField = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        recargarButton = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        misViajesButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        volverButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 450));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACCESO CON TARJETA");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(5, 0));

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jPanel9.setLayout(new java.awt.BorderLayout());

        billetesCompradosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billetesCompradosLabel.setText("Numero de billetes comprados:");
        jPanel9.add(billetesCompradosLabel, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(3, 0));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel19);

        jPanel20.setLayout(new java.awt.BorderLayout());

        billetesCompradosTextField.setEditable(false);
        jPanel20.add(billetesCompradosTextField, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel20);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel21);

        jPanel4.add(jPanel10);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jPanel11.setLayout(new java.awt.BorderLayout());

        saldoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldoLabel.setText("Saldo actual de la tarjeta:");
        jPanel11.add(saldoLabel, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(3, 0));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel22);

        jPanel23.setLayout(new java.awt.BorderLayout());

        saldoTextField.setEditable(false);
        jPanel23.add(saldoTextField, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel23);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel24);

        jPanel5.add(jPanel12);

        jPanel3.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jPanel6.setLayout(new java.awt.BorderLayout());

        recargarButton.setText("Recargar Tarjeta");
        recargarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargarButtonActionPerformed(evt);
            }
        });
        jPanel6.add(recargarButton, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jPanel7.setLayout(new java.awt.BorderLayout());

        misViajesButton.setText("Mis Viajes");
        misViajesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misViajesButtonActionPerformed(evt);
            }
        });
        jPanel7.add(misViajesButton, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jPanel8.setLayout(new java.awt.BorderLayout());

        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        jPanel8.add(volverButton, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel8);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Procesa el evento cuando se hace clic en el botón "Volver", enviando la señal al controlador.
    *
    * @param evt El evento de acción que desencadena este método.
    */

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        miControlador.procesarEventoVolverButton();
    }//GEN-LAST:event_volverButtonActionPerformed

    /**
    * Procesa el evento cuando se hace clic en el botón "Recargar Tarjeta", enviando la señal al controlador.
    *
    * @param evt El evento de acción que desencadena este método.
    */
    
    private void recargarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargarButtonActionPerformed
        miControlador.procesarEventoRecargarTarjetaButton();
    }//GEN-LAST:event_recargarButtonActionPerformed

   
    /**
    * Procesa el evento cuando se hace clic en el botón "Mis Viajes", enviando la señal al controlador.
    *
    * @param evt El evento de acción que desencadena este método.
    */
    
    private void misViajesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misViajesButtonActionPerformed
        miControlador.procesarEventoMisViajesButton();
    }//GEN-LAST:event_misViajesButtonActionPerformed

    /**
    * Establece el texto del saldo en el campo de texto del saldo en la vista.
    *
    * @param saldo El saldo a ser mostrado en la vista.
    */

    public void setTextSaldo(double saldo){
        java.text.DecimalFormat formatodecimal = new java.text.DecimalFormat("#.##");
        String numerodecimal = formatodecimal.format(saldo);
        numerodecimal = numerodecimal+"€";
        saldoTextField.setText(numerodecimal);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billetesCompradosLabel;
    private javax.swing.JTextField billetesCompradosTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton misViajesButton;
    private javax.swing.JToggleButton recargarButton;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JTextField saldoTextField;
    private javax.swing.JToggleButton volverButton;
    // End of variables declaration//GEN-END:variables
}
